#   Theoretical Questions

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

In [ ]:
#solution 1
numpy efficiently handle array which are collection of homogenous data hence calculation is fast
and memory efficient.
numpy perform complex mathematical operation seamlessly and also easily intrgrated with other libraries
all these features enhance pythons capabilities for numerical operation

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

In [ ]:
#solution 2
np.mean() calculate arithmetic mean where as np.average() calculate both 
arithmetic mean as well as weighted average.
if all elements have equal weight then both will give same result
np.average() is more efficient as it calculate both
it does the job for np.mean() also
use np.mean() when all elements have equal weight
when weights are different use np.average()

In [2]:
#examples
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8]) #all elements are of equal weight

In [6]:
np.mean(arr)  #can calculate mean only

4.5

In [7]:
np.average(arr) 

4.5

In [9]:
arr = np.array([1,2,3,4,5,6,7,8])
weight = np.array([2,6,4,7,2,3,5,1])     #weights are different
np.average(arr,weights = weight)         #np.average has argument of weight

4.166666666666667

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D array.

In [16]:
#solution 3
arr1 = np.array([1,2,3,4,5,6])      #1D array
arr2 = np.array([[1,2,3,4],[5,6,7,8]])   #2Darray

In [18]:
np.flip(arr1)      #no need to mention axes in case of 1D

array([6, 5, 4, 3, 2, 1])

In [19]:
np.flip(arr2,axis = 0)    #Flip an array vertically

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [21]:
np.flip(arr2,axis = 1)  #Flip an array horizontally

array([[4, 3, 2, 1],
       [8, 7, 6, 5]])

4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.




In [4]:
#solution 4
numpy is a collection of homogenous data.
To know about the data type use dtype

dtype('int64')

In [5]:
arr =np.array([1,2,3,4,5,6,7])
arr.dtype

dtype('int64')

In [ ]:
data type plays an important role in memory management as it allow the compiler
to allocate right amount of memory for data and perform right operation on it
due to this feature of datatype memory manged corectly and calculation become faster


5. Define ndarrays in NumPy and explain their key features. 
How do they differ from standard Python lists?

In [ ]:
#solution 5
ndarrays are the collection of same type of data,size of data are also same
key features of ndarray in numpy is that  it ideal for handling large datasets, images, 
and other types of numerical data. NumPy arrays are much more efficient 
than Python’s built-in lists, and they offer many additional features that make 
them easier to work with.
difference between ndarray and list are
ndarray can store only homogenous data where as list can store hetrogenous data
list takes huge amount of time and memory for numerical calculation on large dataset
whereas ndarrayb take very less time and memory for numerical calculation on large dataset

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale
numerical operations.

In [4]:
#solution 6
to analyse the performance benefits of Numpy array over lists we will note the time taken 
by both on large scale numerical operation

In [8]:
#example
import numpy as np
import time as t
size = 200000
lst1 = list(range(size))
lst2 = list(range(size))
arr1 = np.arange(size)
arr2 = np.arange(size)


#time calculation for list
begin = t.time()
final_lst = [(a*b) for a,b in zip(lst1,lst2)]
print(f"time taken by python list : {t.time()-begin} seconds")


#time calculation for array
begin = t.time()
final_arr = arr1*arr2
print(f"time taken by numpy array : {t.time()-begin} seconds")

time taken by python list : 0.01838088035583496 seconds
time taken by numpy array : 0.0010471343994140625 seconds


In [ ]:
clearly we can see that list takes more time than numpy array

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

In [ ]:
#solution 7
vstack() is used to stack sequense of input array vertically to make a single array
hstack () is used to stack sequense of input array horizontally to make a single array


In [14]:
#examples
#vstack()
arr1 = np.ones((3,3))
arr2 = np.array([1,2,3])
np.vstack((arr1,arr2))



array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 2., 3.]])

In [15]:
#hstack()
#we cannot use hstack directly.both array should have same number of rows
np.hstack((arr1,arr2))


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [17]:
#to apply hstack we should make both array with same number of rows
arr2 = arr2.reshape(3,1)

In [18]:
#now we can apply hstack
np.hstack((arr1,arr2))


array([[1., 1., 1., 1.],
       [1., 1., 1., 2.],
       [1., 1., 1., 3.]])

8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

In [ ]:
#solution 8
fliplr() >>> array will flip left and right
flipud() >>> array will flip up and down

In [11]:
import numpy as np
arr1 = np.random.randint(3,7,size = 6).reshape(2,3)
arr1


array([[5, 3, 3],
       [3, 5, 6]])

In [12]:
np.fliplr(arr1)     #elements will flip from left to right

array([[3, 3, 5],
       [6, 5, 3]])

In [13]:
np.flipud(arr1)     #elements will flip from up to down

array([[3, 5, 6],
       [5, 3, 3]])

In [14]:
arr2 = np.array([1,2,3,4,5,6])

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [ ]:
#solution 9
array_split method is same as array.split.the only differnce is it handle uneven data for which 
array.split throw an error
array_split method is used to split data into required form i.e. about given axis,to number of arrays and 
about mentioned index


In [13]:
#example
#split data about given axis
import numpy as np
arr1 = np.random.randint(2,17,size = 9).reshape(3,3)
arr1

array([[ 4,  9, 12],
       [16,  5, 16],
       [ 7, 12, 15]])

In [14]:
new_arr1 = np.array_split(arr1,3,axis =0)    #split about axis 0
new_arr1

[array([[ 4,  9, 12]]), array([[16,  5, 16]]), array([[ 7, 12, 15]])]

In [15]:
new_arr1 = np.array_split(arr1,3,axis =1)    #split about axis 0
new_arr1

[array([[ 4],
        [16],
        [ 7]]),
 array([[ 9],
        [ 5],
        [12]]),
 array([[12],
        [16],
        [15]])]

In [19]:
#np.split can't handle uneven split
new_arr1 = np.split(arr1,2)    
new_arr1

ValueError: array split does not result in an equal division

In [20]:
# np.array_split can handle uneven split also

new_arr1 = np.array_split(arr1,2)    
new_arr1

[array([[ 4,  9, 12],
        [16,  5, 16]]),
 array([[ 7, 12, 15]])]

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

In [21]:
#solution 10
vectorization >> it is the process of performing operations between arrays without using for loop.it uses 
broadcasting when array size are different or not compatible with each other


In [31]:
#example
arr1 = np.linspace(2,9,8).reshape(2,4)
arr1

array([[2., 3., 4., 5.],
       [6., 7., 8., 9.]])

In [32]:
arr2 = np.linspace(7,19,8).reshape(2,4)
arr2

array([[ 7.        ,  8.71428571, 10.42857143, 12.14285714],
       [13.85714286, 15.57142857, 17.28571429, 19.        ]])

In [35]:
print(f"sum of arr1 and arr2 is \n{arr1+arr2}")    #vectorization is used here

sum of arr1 and arr2 is 
[[ 9.         11.71428571 14.42857143 17.14285714]
 [19.85714286 22.57142857 25.28571429 28.        ]]


In [ ]:
we didnot use for loop above i.e. we do not apply operation on elements one by one 
instead of which we use vectorization
it gives faster result then for loop

In [ ]:
#broadcasting
broadcasting is used when we have array of different size
it expand the array of smaller size and make it compatible with larger one to perform given operation


In [36]:
#example
arr1 = np.array([1,2,3,4,5])
arr2 = 5     #it will convert into arr(5,5,5,5,5) before operation i.e. called broadcasting
arr1+arr2    #here broadcasting and vectorization both happens

array([ 6,  7,  8,  9, 10])