# Practical Questions

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [2]:
import numpy as np

In [4]:
#solution 1
arr1 = np.random.randint(1,100,9).reshape(3,3)
arr1

array([[31, 35, 46],
       [60, 22, 88],
       [55, 61, 63]])

In [5]:
arr1.T    #transpose will interchange row and columns

array([[31, 60, 55],
       [35, 22, 61],
       [46, 88, 63]])

2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [9]:
#solution 2
arr1 = np.arange(1,11)   #1D array
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#reshape into 2x5 array
arr1.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
#reshape into 5x2 array
arr1.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, 
resulting in a 6x6 array.

In [9]:
import numpy as np
arr = np.linspace(2,8,16).reshape(4,4)
arr

array([[2. , 2.4, 2.8, 3.2],
       [3.6, 4. , 4.4, 4.8],
       [5.2, 5.6, 6. , 6.4],
       [6.8, 7.2, 7.6, 8. ]])

In [10]:
arr1,arr2,arr3,arr4 = np.split(arr,4)

In [25]:
arr1 = np.insert(arr1,0,0)

In [19]:
np.append(arr1,0)

array([0. , 2. , 2.4, 2.8, 3.2, 0. ])

In [62]:
new_arr = np.array([0,0,0,0,0,0])
lst = []
for n in np.split(arr,4):
    i = np.insert(n,0,0)
    i = np.append(i,0)
    lst == lst.append(i)
print(lst)
    
    
    

[array([0. , 2. , 2.4, 2.8, 3.2, 0. ]), array([0. , 3.6, 4. , 4.4, 4.8, 0. ]), array([0. , 5.2, 5.6, 6. , 6.4, 0. ]), array([0. , 6.8, 7.2, 7.6, 8. , 0. ])]


In [65]:
arr1 = np.zeros(6)
arr6 = np.zeros(6)

In [66]:
arr2,arr3,arr4,arr5 = lst

In [74]:
final_arr = np.vstack((arr1,arr2,arr3,arr4,arr5,arr6))
final_arr

array([[0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 2. , 2.4, 2.8, 3.2, 0. ],
       [0. , 3.6, 4. , 4.4, 4.8, 0. ],
       [0. , 5.2, 5.6, 6. , 6.4, 0. ],
       [0. , 6.8, 7.2, 7.6, 8. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. ]])

4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [81]:
#solution 4
arr = np.arange(10,61,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [85]:
#solution 5
str_arr = np.array(['python', 'numpy', 'pandas'])
str_arr

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [86]:
np.char.upper(str_arr)   #uppercase 

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [87]:
np.char.lower(str_arr)  #lowercase

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [88]:
np.char.title(str_arr) #title

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [89]:
np.char. capitalize(str_arr) #capitalize

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [111]:
#solution 6
str_arr = np.array(['python', 'numpy', 'pandas'])
np.char.join(" ",str_arr)

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [118]:
arr1 = np.linspace(6,24,9).reshape(3,3)
arr2 = np.linspace(9,45,9).reshape(3,3)

In [120]:
arr1

array([[ 6.  ,  8.25, 10.5 ],
       [12.75, 15.  , 17.25],
       [19.5 , 21.75, 24.  ]])

In [119]:
arr2

array([[ 9. , 13.5, 18. ],
       [22.5, 27. , 31.5],
       [36. , 40.5, 45. ]])

In [121]:
#addition
arr1+arr2

array([[15.  , 21.75, 28.5 ],
       [35.25, 42.  , 48.75],
       [55.5 , 62.25, 69.  ]])

In [122]:
#multiplication
arr1*arr2

array([[  54.   ,  111.375,  189.   ],
       [ 286.875,  405.   ,  543.375],
       [ 702.   ,  880.875, 1080.   ]])

In [123]:
#subtraction
arr1-arr2

array([[ -3.  ,  -5.25,  -7.5 ],
       [ -9.75, -12.  , -14.25],
       [-16.5 , -18.75, -21.  ]])

In [125]:
#division
arr1/arr2

array([[0.66666667, 0.61111111, 0.58333333],
       [0.56666667, 0.55555556, 0.54761905],
       [0.54166667, 0.53703704, 0.53333333]])

8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [127]:
#SOLUTION 8
identity_arr = np.eye(5)   #5x5 diagonal matrix
identity_arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [129]:
np.diag(identity_arr)    #gives diagonal elements of any matrix

array([1., 1., 1., 1., 1.])

9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [52]:
ran_arr = np.random.randint(0,1000,100)
prime_lst = []
for i in ran_arr:
    if i == 1 or i == 0:
        continue
    else:
        for j in range(2,i):
            if (i%j == 0):
                break
        else:
            prime_lst.append(i)
prime_lst

[383, 53, 109, 307, 379, 241, 457, 929, 349, 727, 293, 827]

10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [30]:
#solution 10
arr = np.random.randint(28,39,35).reshape(5,7)

In [35]:
week_arr = np.split(arr,5,axis = 0)

In [38]:
for n in week_arr:
    weekly_average = np.sum(n)/7
    print("weekly averages of temperature =" , weekly_average)

weekly averages of temperature = 32.42857142857143
weekly averages of temperature = 32.57142857142857
weekly averages of temperature = 32.285714285714285
weekly averages of temperature = 31.857142857142858
weekly averages of temperature = 32.57142857142857
